### ISSUE TITLE
Coupons don't get updated at stitch

### ISSUE THREAD

**Issue by broksonic21** [singer-io/tap-woocommerce#4]
Let's say we pull in (using tap-woocommerce) orders for a few months back

Then refunds come in after the fact, changing the coupons on the order.
So we want to rerun to pull them in.

I see stitch updating (via target-stitch) the last updated date for the orders, but line-items/coupons aren't getting updated 

Is there a way to do this without deleting data from the warehouse?

**Comment by ahaverbuch** [comment]
Note: this is going to redshift

**Comment by broksonic21** [comment]
Note: this is going to redshift, so not sure where the configuration is off, just know it's not working. I do see tap-woocommerce sending the data, but unclear if catalog changes are needed to get this to work.

**Comment by broksonic21** [comment]
user error - ignore this.
